# Generated by Django 4.2.7 on 2025-09-05 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_clientinfo_monthly_revenue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User's first name", max_length=150),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User's last name", max_length=150),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address", max_length=254, unique=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, help_text="Company name", max_length=255, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="User's phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "magic_token",
                    models.CharField(
                        help_text="Unique token for magic link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("magic_link", models.URLField(help_text="Generated magic link URL")),
                (
                    "generated_username",
                    models.CharField(
                        help_text="Auto-generated username", max_length=150, unique=True
                    ),
                ),
                (
                    "generated_password",
                    models.CharField(
                        help_text="Auto-generated temporary password", max_length=128
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether the magic link has been used"
                    ),
                ),
                (
                    "is_account_created",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user account has been created",
                    ),
                ),
                (
                    "webhook_sent",
                    models.BooleanField(
                        default=False, help_text="Whether webhook has been sent to n8n"
                    ),
                ),
                (
                    "webhook_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When webhook was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the magic link expires"),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The created user account (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="magic_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Magic User",
                "verbose_name_plural": "Magic Users",
                "db_table": "magic_users",
                "ordering": ["-created_at"],
            },
        ),
    ]
