# Generated by Django 4.2.7 on 2025-09-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_magicuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for password reset", max_length=254
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique token for password reset",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the reset request was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the reset token expires"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether the reset token has been used"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
                "db_table": "password_resets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="password_re_email_072551_idx",
                    ),
                    models.Index(fields=["token"], name="password_re_token_fb23e2_idx"),
                ],
            },
        ),
    ]
