# Generated by Django 4.2.7 on 2025-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_position_user_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="magicuser",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="User's position in company",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="magicuser",
            name="title",
            field=models.CharField(
                blank=True, help_text="User's job title", max_length=100, null=True
            ),
        ),
    ]
