# Generated by Django 4.2.7 on 2025-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_magicuser_position_magicuser_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="input_tokens_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Total input tokens used by the user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_token_usage_date",
            field=models.DateTimeField(
                blank=True, help_text="Last time user used tokens", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="output_tokens_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Total output tokens used by the user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_tokens_used",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of tokens used by the user"
            ),
        ),
    ]
