# Generated by Django 4.2.7 on 2025-09-19 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_alter_file_bucket_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code for folder", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subfolders",
                to="files.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder containing this file",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="files.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["user", "folder"], name="files_user_id_fa6e25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["folder", "created_at"], name="files_folder__2849c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["user", "parent"], name="folders_user_id_0d7266_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["created_at"], name="folders_created_bcede5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("user", "parent", "name")},
        ),
    ]
