# Generated by Django 4.2.7 on 2025-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatmessage_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="input_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of input tokens used for this message",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="output_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of output tokens used for this message",
                null=True,
            ),
        ),
    ]
