# Generated by Django 4.2.7 on 2025-09-19 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_chatmessage_input_tokens_chatmessage_output_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
